# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DXx0LmpuCYeC_GWDxmujdSv5kPEM98QD
"""

#The whole code in one cell
# tokenizer_experiment.py
# Goal:
# Test whether constrained morphology-aware tokenization reduces token fragmentation
# in Polish compared to Spanish.

!pip install evaluate
!pip install sacrebleu
!pip install morfessor
!pip install evaluate sacrebleu transformers sentencepiece -q

from __future__ import annotations

import json
import math
import os
import random
import re
import statistics
from collections import Counter
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import List, Sequence

from datasets import load_dataset
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.trainers import BpeTrainer


# =============================
# Config
# =============================

SPANISH_SUFFIXES = sorted({
    "mente", "ciones", "ción", "adoras", "adores", "adora", "ador",
    "idades", "idad", "ismos", "ismo", "istas", "ista", "anzas", "anza",
    "amiento", "imientos", "imiento", "ando", "iendo", "ados", "adas",
    "ado", "ada", "idos", "idas", "ido", "ida", "amos", "emos", "imos",
    "aré", "eré", "iré", "aba", "ía", "ías", "aron",
}, key=len, reverse=True)

POLISH_SUFFIXES = sorted({
    "owego", "ami", "owie", "owiec", "owień", "izacja", "izacje",
    "enia", "enie", "anie", "aniu", "eniem", "aniem", "owych", "owej",
    "owym", "owymi", "kach", "kami", "kom", "ką", "ki", "ka", "ku",
    "ach", "owi", "ego", "emu", "ie", "em", "om", "ą", "ę",
}, key=len, reverse=True)


# =============================
# Basic utilities
# =============================

def normalize_whitespace(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def simple_word_tokenize(text: str) -> List[str]:
    return re.findall(r"\w+|[^\w\s]", text, flags=re.UNICODE)


def is_word(token: str) -> bool:
    return bool(re.match(r"^\w+$", token, flags=re.UNICODE))


def write_lines(path: str | Path, lines: Sequence[str]) -> None:
    os.makedirs(Path(path).parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")


def read_lines(path: str | Path) -> List[str]:
    with open(path, "r", encoding="utf-8") as f:
        return [line.rstrip("\n") for line in f]


def build_word_freq(lines: Sequence[str]) -> Counter:
    freq = Counter()
    for line in lines:
        for tok in simple_word_tokenize(line):
            if is_word(tok):
                freq[tok.lower()] += 1
    return freq


# =============================
# Dataset
# =============================

def download_and_prepare_europarl(
    lang: str,
    output_dir: str,
    max_train: int = 10000,
    max_valid: int = 1000,
):
    lang_code = {"spanish": "es", "polish": "pl"}[lang]
    config = f"en-{lang_code}"

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    ds = load_dataset("Helsinki-NLP/europarl", config)
    rows = ds["train"]

    src_lines, tgt_lines = [], []

    for ex in rows:
        trans = ex["translation"]

        src = normalize_whitespace(trans[lang_code])
        tgt = normalize_whitespace(trans["en"])

        if src and tgt:
            src_lines.append(src)
            tgt_lines.append(tgt)

        if len(src_lines) >= max_train + max_valid:
            break

    files = {
        "train_src": str(out / f"train.{lang_code}"),
        "train_tgt": str(out / "train.en"),
        "valid_src": str(out / f"valid.{lang_code}"),
        "valid_tgt": str(out / "valid.en"),
    }

    write_lines(files["train_src"], src_lines[:max_train])
    write_lines(files["train_tgt"], tgt_lines[:max_train])
    write_lines(files["valid_src"], src_lines[max_train:max_train + max_valid])
    write_lines(files["valid_tgt"], tgt_lines[max_train:max_train + max_valid])

    return files


# =============================
# Tokenization methods
# =============================

def split_suffix_once(word: str, lang: str) -> str:
    suffixes = SPANISH_SUFFIXES if lang == "spanish" else POLISH_SUFFIXES
    lower = word.lower()

    for suffix in suffixes:
        if len(lower) > len(suffix) + 2 and lower.endswith(suffix):
            stem = word[:-len(suffix)]
            ending = word[-len(suffix):]
            return f"{stem} @@ {ending}"

    return word


def rare_long_morph_line(
    line: str,
    lang: str,
    word_freq: Counter,
    max_freq: int,
    min_len: int,
) -> str:
    pieces = []

    for tok in simple_word_tokenize(line):
        if is_word(tok):
            word = tok.lower()

            if word_freq[word] < max_freq and len(word) >= min_len:
                pieces.append(split_suffix_once(tok, lang))
            else:
                pieces.append(tok)
        else:
            pieces.append(tok)

    return normalize_whitespace(" ".join(pieces))


# =============================
# BPE training
# =============================

def train_bpe_tokenizer(
    train_file: str | Path,
    vocab_size: int,
    save_dir: str | Path,
) -> Tokenizer:
    os.makedirs(save_dir, exist_ok=True)

    tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
    tokenizer.pre_tokenizer = Whitespace()

    trainer = BpeTrainer(
        vocab_size=vocab_size,
        special_tokens=["[UNK]", "[PAD]", "[BOS]", "[EOS]"],
        show_progress=False,
    )

    tokenizer.train([str(train_file)], trainer)
    tokenizer.save(str(Path(save_dir) / "tokenizer.json"))

    return tokenizer


# =============================
# Metrics
# =============================

@dataclass
class FragmentationMetrics:
    mean_tokens_per_word: float
    median_tokens_per_word: float
    p90_tokens_per_word: float
    mean_tokens_per_sentence: float
    examples_checked: int


def compute_fragmentation_metrics(
    tokenizer: Tokenizer,
    lines: Sequence[str],
    max_sentences: int = 200,
) -> FragmentationMetrics:
    selected = list(lines[:max_sentences])

    sent_token_counts = []
    word_token_counts = []

    for line in selected:
        sent_token_counts.append(len(tokenizer.encode(line).tokens))

        for word in simple_word_tokenize(line):
            if is_word(word):
                word_token_counts.append(len(tokenizer.encode(word).tokens))

    sorted_counts = sorted(word_token_counts)
    p90_idx = min(len(sorted_counts) - 1, math.floor(0.9 * len(sorted_counts)))

    return FragmentationMetrics(
        mean_tokens_per_word=statistics.mean(word_token_counts),
        median_tokens_per_word=statistics.median(word_token_counts),
        p90_tokens_per_word=float(sorted_counts[p90_idx]),
        mean_tokens_per_sentence=statistics.mean(sent_token_counts),
        examples_checked=len(selected),
    )


def sample_words(lines: Sequence[str], min_len: int = 5, max_items: int = 1000):
    counter = Counter()

    for line in lines:
        for tok in simple_word_tokenize(line):
            if is_word(tok) and len(tok) >= min_len:
                counter[tok.lower()] += 1

    return [w for w, _ in counter.most_common(max_items)]


def inspect_word_splits(tokenizer: Tokenizer, words: Sequence[str]):
    return [
        {"word": word, "tokens": tokenizer.encode(word).tokens}
        for word in words
    ]


# =============================
# Main experiment
# =============================

def train_and_eval_system(
    name: str,
    train_lines: Sequence[str],
    valid_lines: Sequence[str],
    out_dir: Path,
    vocab_size: int,
):
    train_path = out_dir / f"{name}_train.txt"
    write_lines(train_path, train_lines)

    tokenizer = train_bpe_tokenizer(
        train_file=train_path,
        vocab_size=vocab_size,
        save_dir=out_dir / name,
    )

    metrics = compute_fragmentation_metrics(tokenizer, valid_lines)

    words = sample_words(valid_lines, min_len=5, max_items=1000)
    examples = inspect_word_splits(tokenizer, words)

    return {
        "metrics": asdict(metrics),
        "examples": examples,
    }


def run_rare_long_grid_search(
    train_src_path: str,
    valid_src_path: str,
    lang: str,
    output_dir: str,
    vocab_size: int = 8000,
    max_freq_values=(2, 3, 5, 8),
    min_len_values=(8, 10, 12, 15),
):
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    train_src = [
        normalize_whitespace(x)
        for x in read_lines(train_src_path)
        if normalize_whitespace(x)
    ]

    valid_src = [
        normalize_whitespace(x)
        for x in read_lines(valid_src_path)
        if normalize_whitespace(x)
    ]

    word_freq = build_word_freq(train_src)

    systems = {}

    systems["baseline_bpe"] = train_src

    for max_freq in max_freq_values:
        for min_len in min_len_values:
            system_name = f"rare_long_freq{max_freq}_len{min_len}"

            systems[system_name] = [
                rare_long_morph_line(
                    line=line,
                    lang=lang,
                    word_freq=word_freq,
                    max_freq=max_freq,
                    min_len=min_len,
                )
                for line in train_src
            ]

    results = {}

    for name, train_lines in systems.items():
        print(f"Training system: {name}")

        results[name] = train_and_eval_system(
            name=name,
            train_lines=train_lines,
            valid_lines=valid_src,
            out_dir=out_dir,
            vocab_size=vocab_size,
        )

    baseline_word = results["baseline_bpe"]["metrics"]["mean_tokens_per_word"]
    baseline_sent = results["baseline_bpe"]["metrics"]["mean_tokens_per_sentence"]

    comparison = []

    for name, data in results.items():
        metrics = data["metrics"]

        comparison.append({
            "system": name,
            "mean_tokens_per_word": metrics["mean_tokens_per_word"],
            "mean_tokens_per_sentence": metrics["mean_tokens_per_sentence"],
            "delta_word_vs_baseline": metrics["mean_tokens_per_word"] - baseline_word,
            "delta_sent_vs_baseline": metrics["mean_tokens_per_sentence"] - baseline_sent,
        })

    comparison = sorted(comparison, key=lambda x: x["mean_tokens_per_word"])

    final_output = {
        "language": lang,
        "vocab_size": vocab_size,
        "comparison": comparison,
        "all_results": results,
    }

    with open(out_dir / "rare_long_grid_results.json", "w", encoding="utf-8") as f:
        json.dump(final_output, f, ensure_ascii=False, indent=2)

    return final_output


# =============================
# Analysis helpers
# =============================

def get_row(results, system_name):
    for row in results["comparison"]:
        if row["system"] == system_name:
            return row
    raise ValueError(f"System not found: {system_name}")


def changed_examples(
    results,
    baseline_name="baseline_bpe",
    method_name="rare_long_freq2_len8",
    max_examples=25,
):
    baseline_examples = results["all_results"][baseline_name]["examples"]
    method_examples = results["all_results"][method_name]["examples"]

    baseline_map = {ex["word"]: ex["tokens"] for ex in baseline_examples}
    method_map = {ex["word"]: ex["tokens"] for ex in method_examples}

    changed = []

    for word in method_map:
        if word not in baseline_map:
            continue

        baseline_tokens = baseline_map[word]
        method_tokens = method_map[word]

        if baseline_tokens != method_tokens:
            changed.append({
                "word": word,
                "baseline_tokens": baseline_tokens,
                "method_tokens": method_tokens,
                "baseline_token_count": len(baseline_tokens),
                "method_token_count": len(method_tokens),
                "token_count_change": len(method_tokens) - len(baseline_tokens),
            })

    changed = sorted(changed, key=lambda x: x["token_count_change"])

    return changed[:max_examples]

import torch
import evaluate
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

bleu_metric = evaluate.load("sacrebleu")
chrf_metric = evaluate.load("chrf")


def evaluate_mt_quality(src_path, tgt_path, model_name, max_examples=300):
    src_lines = read_lines(src_path)[:max_examples]
    tgt_lines = read_lines(tgt_path)[:max_examples]

    tok = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model.to(device)
    model.eval()

    preds = []

    for line in src_lines:
        batch = tok(
            line,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=128,
        ).to(device)

        with torch.no_grad():
            output = model.generate(**batch, max_length=128)

        pred = tok.decode(output[0], skip_special_tokens=True)
        preds.append(pred)

    bleu = bleu_metric.compute(
        predictions=preds,
        references=[[x] for x in tgt_lines],
    )

    chrf = chrf_metric.compute(
        predictions=preds,
        references=tgt_lines,
    )

    return {
        "model_name": model_name,
        "num_examples": len(src_lines),
        "bleu": bleu["score"],
        "chrf": chrf["score"],
        "examples": [
            {
                "src": src_lines[i],
                "pred": preds[i],
                "ref": tgt_lines[i],
            }
            for i in range(min(5, len(src_lines)))
        ],
    }

def make_summary(
    polish_results,
    spanish_results,
    best_system="rare_long_freq2_len8",
    output_path="tokenization_experiment_summary.txt",
):
    polish_base = get_row(polish_results, "baseline_bpe")
    polish_best = get_row(polish_results, best_system)

    spanish_base = get_row(spanish_results, "baseline_bpe")
    spanish_best = get_row(spanish_results, best_system)

    polish_examples = changed_examples(
        polish_results,
        baseline_name="baseline_bpe",
        method_name=best_system,
        max_examples=20,
    )

    lines = []

    lines.append("Tokenization Experiment Summary")
    lines.append("=" * 70)
    lines.append("")
    lines.append("Research question:")
    lines.append(
        "Can constrained morphology-aware tokenization reduce token fragmentation "
        "in a morphologically richer language?"
    )
    lines.append("")

    lines.append("Best method:")
    lines.append(best_system)
    lines.append("")

    lines.append("Polish:")
    lines.append(
        f"baseline_bpe: tokens/word={polish_base['mean_tokens_per_word']:.6f}, "
        f"tokens/sentence={polish_base['mean_tokens_per_sentence']:.6f}"
    )
    lines.append(
        f"{best_system}: tokens/word={polish_best['mean_tokens_per_word']:.6f}, "
        f"tokens/sentence={polish_best['mean_tokens_per_sentence']:.6f}"
    )
    lines.append(
        f"Change: tokens/word={polish_best['delta_word_vs_baseline']:.6f}, "
        f"tokens/sentence={polish_best['delta_sent_vs_baseline']:.6f}"
    )
    lines.append("")

    lines.append("Spanish:")
    lines.append(
        f"baseline_bpe: tokens/word={spanish_base['mean_tokens_per_word']:.6f}, "
        f"tokens/sentence={spanish_base['mean_tokens_per_sentence']:.6f}"
    )
    lines.append(
        f"{best_system}: tokens/word={spanish_best['mean_tokens_per_word']:.6f}, "
        f"tokens/sentence={spanish_best['mean_tokens_per_sentence']:.6f}"
    )
    lines.append(
        f"Change: tokens/word={spanish_best['delta_word_vs_baseline']:.6f}, "
        f"tokens/sentence={spanish_best['delta_sent_vs_baseline']:.6f}"
    )
    lines.append("")

    lines.append("Changed Polish examples:")
    for ex in polish_examples:
        lines.append(
            f"- {ex['word']}: "
            f"{ex['baseline_tokens']} ({ex['baseline_token_count']}) -> "
            f"{ex['method_tokens']} ({ex['method_token_count']}), "
            f"change={ex['token_count_change']}"
        )

    lines.append("")
    lines.append("Interpretation:")
    lines.append(
        "The constrained rare+long morphology-aware method slightly reduces "
        "token fragmentation for Polish, while the same method does not help Spanish."
    )
    lines.append(
        "This suggests the benefit may be language-dependent and more relevant for "
        "morphologically richer languages."
    )
    lines.append(
        "This is tokenizer-level evidence. The next step is controlled MT training "
        "to test BLEU/chrF."
    )

    text = "\n".join(lines)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(text)

    print(text)
    print("\nSaved:", output_path)

    return text

def make_summary_with_mt(
    polish_results,
    spanish_results,
    polish_mt_results,
    spanish_mt_results,
    best_system="rare_long_freq2_len8",
    output_path="tokenization_experiment_summary_with_mt.txt",
):
    polish_base = get_row(polish_results, "baseline_bpe")
    polish_best = get_row(polish_results, best_system)

    spanish_base = get_row(spanish_results, "baseline_bpe")
    spanish_best = get_row(spanish_results, best_system)

    polish_examples = changed_examples(
        polish_results,
        baseline_name="baseline_bpe",
        method_name=best_system,
        max_examples=20,
    )

    lines = []

    lines.append("Tokenization Experiment Summary")
    lines.append("=" * 70)
    lines.append("")
    lines.append("Research question:")
    lines.append(
        "Can constrained morphology-aware tokenization reduce token fragmentation "
        "in a morphologically richer language?"
    )
    lines.append("")

    lines.append("Best method:")
    lines.append(best_system)
    lines.append("")

    lines.append("Polish tokenizer results:")
    lines.append(
        f"baseline_bpe: tokens/word={polish_base['mean_tokens_per_word']:.6f}, "
        f"tokens/sentence={polish_base['mean_tokens_per_sentence']:.6f}"
    )
    lines.append(
        f"{best_system}: tokens/word={polish_best['mean_tokens_per_word']:.6f}, "
        f"tokens/sentence={polish_best['mean_tokens_per_sentence']:.6f}"
    )
    lines.append(
        f"Change: tokens/word={polish_best['delta_word_vs_baseline']:.6f}, "
        f"tokens/sentence={polish_best['delta_sent_vs_baseline']:.6f}"
    )
    lines.append("")

    lines.append("Spanish tokenizer results:")
    lines.append(
        f"baseline_bpe: tokens/word={spanish_base['mean_tokens_per_word']:.6f}, "
        f"tokens/sentence={spanish_base['mean_tokens_per_sentence']:.6f}"
    )
    lines.append(
        f"{best_system}: tokens/word={spanish_best['mean_tokens_per_word']:.6f}, "
        f"tokens/sentence={spanish_best['mean_tokens_per_sentence']:.6f}"
    )
    lines.append(
        f"Change: tokens/word={spanish_best['delta_word_vs_baseline']:.6f}, "
        f"tokens/sentence={spanish_best['delta_sent_vs_baseline']:.6f}"
    )
    lines.append("")

    lines.append("MT reference evaluation:")
    lines.append(
        f"Polish→English pretrained MT: BLEU={polish_mt_results['bleu']:.4f}, "
        f"chrF={polish_mt_results['chrf']:.4f}, "
        f"examples={polish_mt_results['num_examples']}"
    )
    lines.append(
        f"Spanish→English pretrained MT: BLEU={spanish_mt_results['bleu']:.4f}, "
        f"chrF={spanish_mt_results['chrf']:.4f}, "
        f"examples={spanish_mt_results['num_examples']}"
    )
    lines.append(
        "Note: this MT evaluation uses pretrained Helsinki-NLP models. "
        "It is a downstream quality reference, not a controlled test of the custom tokenizer."
    )
    lines.append("")

    lines.append("Changed Polish examples:")
    for ex in polish_examples:
        lines.append(
            f"- {ex['word']}: "
            f"{ex['baseline_tokens']} ({ex['baseline_token_count']}) -> "
            f"{ex['method_tokens']} ({ex['method_token_count']}), "
            f"change={ex['token_count_change']}"
        )

    lines.append("")
    lines.append("Interpretation:")
    lines.append(
        "The constrained rare+long morphology-aware method slightly reduces "
        "token fragmentation for Polish, while the same method worsens Spanish."
    )
    lines.append(
        "This suggests the benefit may be language-dependent and more relevant for "
        "morphologically richer languages."
    )
    lines.append(
        "The next step is controlled MT training/fine-tuning using each tokenizer "
        "to test whether this token efficiency preserves BLEU/chrF."
    )

    text = "\n".join(lines)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(text)

    print(text)
    print("\nSaved:", output_path)

    return text

# =============================
# Run everything
# =============================

# Polish
polish_files = download_and_prepare_europarl(
    lang="polish",
    output_dir="data/europarl_pl_en",
    max_train=10000,
    max_valid=1000,
)

polish_results = run_rare_long_grid_search(
    train_src_path=polish_files["train_src"],
    valid_src_path=polish_files["valid_src"],
    lang="polish",
    output_dir="runs/polish_rare_long_grid",
    vocab_size=8000,
)

# Spanish
spanish_files = download_and_prepare_europarl(
    lang="spanish",
    output_dir="data/europarl_es_en",
    max_train=10000,
    max_valid=1000,
)

spanish_results = run_rare_long_grid_search(
    train_src_path=spanish_files["train_src"],
    valid_src_path=spanish_files["valid_src"],
    lang="spanish",
    output_dir="runs/spanish_rare_long_grid",
    vocab_size=8000,
)

polish_mt_results = evaluate_mt_quality(
    src_path=polish_files["valid_src"],
    tgt_path=polish_files["valid_tgt"],
    model_name="Helsinki-NLP/opus-mt-pl-en",
    max_examples=300,
)

print(polish_mt_results["bleu"])
print(polish_mt_results["chrf"])

spanish_mt_results = evaluate_mt_quality(
    src_path=spanish_files["valid_src"],
    tgt_path=spanish_files["valid_tgt"],
    model_name="Helsinki-NLP/opus-mt-es-en",
    max_examples=300,
)

print(spanish_mt_results["bleu"])
print(spanish_mt_results["chrf"])

# Final summary
summary_with_mt = make_summary_with_mt(
    polish_results=polish_results,
    spanish_results=spanish_results,
    polish_mt_results=polish_mt_results,
    spanish_mt_results=spanish_mt_results,
    best_system="rare_long_freq2_len8",
)
